name 'Nelmo-logstash'
version '1.0.0'
description "This module installs and manages logstash software and configuration.
Through declaration, you can configure directors and configuration files.
It's usable on Debian 5/6 & Redhat 4/5/6 systems."
project_page 'https://github.com/nelmos/puppet.git'
author 'nelmo - cedrik MALLET'


